name: Sync with Sway

on:
  schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours, adjust as needed
  push:
    branches:
      master

jobs:
  sync:
    runs-on: ubuntu-latest

    permissions:
      contents: write


    steps:
    - name: Checkout std-mirror
      uses: actions/checkout@v2
      with:
        repository: 'FuelLabs/sway-std'
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Check Latest Release in Sway Repo
      id: sway-repo-release
      run: |
        LATEST_TAG=$(curl -s https://api.github.com/repos/FuelLabs/sway/releases/latest | jq -r '.tag_name')
        echo "Latest Release Tag in Sway is $LATEST_TAG"
        echo "::set-output name=tag::$LATEST_TAG"

    - name: Clone Specific Directories from Sway Repo
      if: steps.sway-repo-release.outputs.tag != ''
      run: |
        git clone --no-checkout https://github.com/FuelLabs/sway
        cd sway
        git sparse-checkout init --cone
        git sparse-checkout set sway-lib-std sway-lib-core 
        git checkout
        cd ..

    - name: Copy directories to sway-std
      if: steps.sway-repo-release.outputs.tag != ''
      run: |
        rm -rf sway-lib-std
        rm -rf sway-lib-core
        mv sway/sway-lib-std sway-lib-std/
        mv sway/sway-lib-core sway-lib-core/
        rm -rf sway

    - name: Commit & Push Changes
      if: steps.sway-repo-release.outputs.tag != ''
      uses: stefanzweifel/git-auto-commit-action@v5

    - name: Create a new tag in sway-std
      if: steps.sway-repo-release.outputs.tag != ''
      run: |
        git tag ${{ steps.sway-repo-release.outputs.tag }}
        git push origin ${{ steps.sway-repo-release.outputs.tag }}

